baseurl = "https://kvar-ispw17.tk"
title = "KiLExq Studio's"
copyright = "Copyright (c) 2017 - 2018, Kvar_ispw17 all rights reserved."
languageCode = "en-US"
canonifyurls = true
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = "kilexq-studio"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "vim" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "About"
  weight = -100
  identifier = "about"
  url = "/about/"

[author]
  name = ""

[params.meta]
  keywords = ""
  description = "KiLExq Studio's Official Website"

[params]
  email = "enkerewpo@gmail.com"
  github = "enkerewpo"
  #gitlab = "gitlab id"
  twitter = "Kvar_ispw17"
  #linkedin = "linkedin id"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#3a91d8"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color

#Font Commercial License http://brittneymurphydesign.com/downloads/alphabetized-cassette-tapes/